import {
  LayoutDashboard,
  Users,
  UserPlus,
  FileText,
  Receipt,
  Wallet,
  UsersRound,
  CheckSquare,
  Sparkles,
  BookOpen,
  Bell,
  Settings,
  BarChart3,
  Calendar,
  MessageSquare,
  Package,
  FileBarChart,
  CreditCard,
  Building2,
  StickyNote,
  Shield,
  FileSpreadsheet,
  Bot,
  Zap,
  Mail,
  Workflow,
  Phone,
  Inbox,
  Mic,
  CalendarClock,
  GraduationCap,
  Globe,
  TrendingUp,
  Key,
  Server,
  Wand2,
  AppWindow,
  FormInput,
  GitBranch,
  Store,
  Activity,
  DollarSign,
  Palette,
  Code,
  Brain,
  Cpu,
  Database,
  Layers,
  FileSearch,
  Target,
  AlertTriangle,
  FileCheck,
  Eye,
  PieChart,
  LineChart,
  Gauge,
  Lightbulb,
  AlertOctagon,
  MessagesSquare,
  FolderKanban,
  Video,
  Megaphone,
  Contact,
  PenTool,
  Search,
  PiggyBank,
  ShoppingCart,
  Truck,
  Warehouse,
  Monitor,
  Calculator,
  List,
  Briefcase,
  Award,
  Clock,
  UserCheck,
  UserX,
  Heart,
  Send,
  Smartphone,
  Share2,
  Gift,
  Radio,
  ArrowRightLeft,
  Plug,
  Lock,
} from 'lucide-react';

export type NavItem = {
  label: string;
  href: string;
  icon: typeof LayoutDashboard;
  badge?: string;
};

export type NavSection = {
  title: string;
  items: NavItem[];
};

export const navSections: NavSection[] = [
  {
    title: 'Overview',
    items: [
      { label: 'Dashboard', href: '/dashboard', icon: LayoutDashboard },
      { label: 'Analytics', href: '/analytics', icon: BarChart3 },
      { label: 'Reports', href: '/reports', icon: FileSpreadsheet },
    ],
  },
  {
    title: 'Sales',
    items: [
      { label: 'Leads', href: '/leads', icon: UserPlus },
      { label: 'Customers', href: '/customers', icon: Users },
      { label: 'Quotations', href: '/quotations', icon: Receipt },
      { label: 'Invoices', href: '/invoices', icon: FileText },
      { label: 'Payments', href: '/payments', icon: Wallet },
    ],
  },
  {
    title: 'Services',
    items: [
      { label: 'Services', href: '/services', icon: Package },
      { label: 'GST Slabs', href: '/gst-slabs', icon: CreditCard },
    ],
  },
  {
    title: 'Operations',
    items: [
      { label: 'Tasks', href: '/tasks', icon: CheckSquare },
      { label: 'Projects', href: '/projects', icon: Layers },
      { label: 'Employees', href: '/employees', icon: UsersRound },
      { label: 'Attendance', href: '/employees/attendance', icon: CalendarClock },
      { label: 'Leaves', href: '/employees/leaves', icon: Calendar },
      { label: 'Payroll', href: '/employees/payroll', icon: Wallet },
      { label: 'Calendar', href: '/calendar', icon: Calendar },
    ],
  },
  {
    title: 'Finance & Operations',
    items: [
      { label: 'Finance Dashboard', href: '/finance', icon: LayoutDashboard },
      { label: 'Chart of Accounts', href: '/finance/chart-of-accounts', icon: FileSpreadsheet },
      { label: 'Journal Entries', href: '/finance/journal', icon: BookOpen },
      { label: 'Budgets', href: '/finance/budgets', icon: PiggyBank },
      { label: 'Vendors', href: '/finance/vendors', icon: Users },
      { label: 'Purchase Orders', href: '/finance/purchase-orders', icon: ShoppingCart },
      { label: 'Inventory', href: '/finance/inventory', icon: Package },
      { label: 'Warehouses', href: '/finance/warehouses', icon: Warehouse },
      { label: 'Assets', href: '/finance/assets', icon: Monitor },
      { label: 'GST & Tax', href: '/finance/tax', icon: Calculator },
    ],
  },
  {
    title: 'HRMS',
    items: [
      { label: 'HR Dashboard', href: '/hr', icon: LayoutDashboard },
      { label: 'Organization', href: '/hr/organization', icon: Building2 },
      { label: 'Employees', href: '/hr/employees', icon: Users },
      { label: 'Recruitment', href: '/hr/recruitment', icon: Briefcase },
      { label: 'Onboarding', href: '/hr/onboarding', icon: UserPlus },
      { label: 'Attendance', href: '/hr/attendance', icon: Clock },
      { label: 'Leaves', href: '/hr/leaves', icon: Calendar },
      { label: 'Shifts', href: '/hr/shifts', icon: CalendarClock },
      { label: 'Payroll', href: '/hr/payroll', icon: DollarSign },
      { label: 'Performance', href: '/hr/performance', icon: Target },
      { label: 'Learning', href: '/hr/learning', icon: GraduationCap },
      { label: 'Exit Mgmt', href: '/hr/exit', icon: UserX },
      { label: 'HR Analytics', href: '/hr/analytics', icon: BarChart3 },
    ],
  },
  {
    title: 'Marketing Cloud',
    items: [
      { label: 'Command Center', href: '/marketing', icon: LayoutDashboard },
      { label: 'Campaigns', href: '/marketing/campaigns', icon: Megaphone },
      { label: 'Landing Pages', href: '/marketing/landing-pages', icon: Globe },
      { label: 'AI Content Studio', href: '/marketing/content', icon: Sparkles, badge: 'AI' },
      { label: 'Email Marketing', href: '/marketing/email', icon: Mail },
      { label: 'WhatsApp Marketing', href: '/marketing/whatsapp', icon: MessageSquare },
      { label: 'SMS Marketing', href: '/marketing/sms', icon: Smartphone },
      { label: 'Social Media', href: '/marketing/social', icon: Share2 },
      { label: 'Automation', href: '/marketing/automation', icon: Zap },
      { label: 'Lead Scoring', href: '/marketing/lead-scoring', icon: Target },
      { label: 'Segments', href: '/marketing/segments', icon: Users },
      { label: 'SEO Toolkit', href: '/marketing/seo', icon: Search },
      { label: 'Digital Ads', href: '/marketing/ads', icon: Radio },
      { label: 'Journey Analytics', href: '/marketing/journey', icon: ArrowRightLeft },
      { label: 'Loyalty & Referrals', href: '/marketing/loyalty', icon: Gift },
      { label: 'Analytics', href: '/marketing/analytics', icon: BarChart3 },
    ],
  },
  {
    title: 'Intelligence',
    items: [
      { label: 'AI CEO', href: '/ai-ceo', icon: Sparkles, badge: 'AI' },
      { label: 'CEO Dashboard', href: '/ceo-dashboard', icon: LayoutDashboard },
      { label: 'Digital Twin', href: '/digital-twin', icon: Building2 },
      { label: 'AI Coach', href: '/ai-coach', icon: GraduationCap },
      { label: 'Simulator', href: '/business-simulator', icon: BarChart3 },
      { label: 'AI Assistant', href: '/assistant', icon: Sparkles },
      { label: 'AI Agents', href: '/ai-agents', icon: Bot },
      { label: 'Workflows', href: '/ai-workflows', icon: Zap },
      { label: 'Knowledge Base', href: '/knowledge', icon: BookOpen },
      { label: 'WhatsApp', href: '/whatsapp', icon: MessageSquare },
      { label: 'Notifications', href: '/notifications', icon: Bell },
    ],
  },
  {
    title: 'Automation',
    items: [
      { label: 'Workflow Builder', href: '/automation', icon: Workflow, badge: 'New' },
      { label: 'AI Generator', href: '/ai-workflow-generator', icon: Sparkles },
      { label: 'Email Campaigns', href: '/email-campaigns', icon: Mail },
      { label: 'WA Campaigns', href: '/wa-campaigns', icon: MessageSquare },
      { label: 'Business Rules', href: '/business-rules', icon: Zap },
    ],
  },
  {
    title: 'AI Builder',
    items: [
      { label: 'AI Command Center', href: '/ai-builder', icon: Wand2 },
      { label: 'Website Builder', href: '/ai-builder/website', icon: Globe },
      { label: 'Dashboard Builder', href: '/ai-builder/dashboards', icon: LayoutDashboard },
      { label: 'Form Builder', href: '/ai-builder/forms', icon: FormInput },
      { label: 'App Builder', href: '/ai-builder/apps', icon: AppWindow },
      { label: 'Report Builder', href: '/ai-builder/reports', icon: FileBarChart },
      { label: 'Workflow Studio', href: '/ai-builder/workflows', icon: GitBranch },
      { label: 'Marketplace', href: '/ai-builder/marketplace', icon: Store },
    ],
  },
  {
    title: 'AI Platform',
    items: [
      { label: 'Overview', href: '/ai-platform', icon: Brain },
      { label: 'Model Router', href: '/ai-platform/model-router', icon: Cpu },
      { label: 'Prompts', href: '/ai-platform/prompts', icon: BookOpen },
      { label: 'Knowledge', href: '/ai-platform/knowledge', icon: Database },
      { label: 'Memory', href: '/ai-platform/memory', icon: Layers },
      { label: 'Vector Search', href: '/ai-platform/vector-search', icon: FileSearch },
      { label: 'Guardrails', href: '/ai-platform/guardrails', icon: Shield },
      { label: 'Doc Intelligence', href: '/ai-platform/document-intelligence', icon: FileText },
      { label: 'Evaluation', href: '/ai-platform/evaluation', icon: Target },
      { label: 'Costs', href: '/ai-platform/costs', icon: DollarSign },
      { label: 'Observability', href: '/ai-platform/observability', icon: Activity },
      { label: 'Approvals', href: '/ai-platform/approvals', icon: CheckSquare },
    ],
  },
  {
    title: 'Communications',
    items: [
      { label: 'Unified Inbox', href: '/inbox', icon: Inbox, badge: 'New' },
      { label: 'AI Receptionist', href: '/receptionist', icon: Phone },
      { label: 'Voice Assistant', href: '/voice-assistant', icon: Mic },
      { label: 'Appointments', href: '/appointments', icon: CalendarClock },
    ],
  },
  {
    title: 'Integration Hub',
    items: [
      { label: 'Command Center', href: '/integration', icon: LayoutDashboard },
      { label: 'API Gateway', href: '/integration/api-gateway', icon: Key },
      { label: 'Webhooks', href: '/integration/webhooks', icon: Zap },
      { label: 'Event Bus', href: '/integration/events', icon: GitBranch },
      { label: 'AI Routing', href: '/integration/ai-routing', icon: Brain },
      { label: 'Connectors', href: '/integration/connectors', icon: Plug },
      { label: 'Marketplace', href: '/integration/marketplace', icon: Store },
      { label: 'Developer', href: '/integration/developer', icon: Code },
      { label: 'Monitoring', href: '/integration/monitoring', icon: Activity },
      { label: 'Secrets', href: '/integration/secrets', icon: Lock },
    ],
  },
  {
    title: 'Security',
    items: [
      { label: 'Security Center', href: '/security', icon: Shield, badge: 'SOC' },
      { label: 'Incidents', href: '/security/incidents', icon: AlertTriangle },
      { label: 'Compliance', href: '/security/compliance', icon: FileCheck },
      { label: 'Audit Log', href: '/security/audit-log', icon: Eye },
    ],
  },
  {
    title: 'BI & Analytics',
    items: [
      { label: 'CEO Dashboard', href: '/bi/ceo-dashboard', icon: PieChart },
      { label: 'Analytics', href: '/bi/analytics', icon: BarChart3 },
      { label: 'KPI Library', href: '/bi/kpis', icon: Gauge },
      { label: 'AI Insights', href: '/bi/insights', icon: Lightbulb, badge: 'AI' },
      { label: 'Anomalies', href: '/bi/anomalies', icon: AlertOctagon },
      { label: 'Forecasts', href: '/bi/forecasts', icon: LineChart },
      { label: 'Data Catalog', href: '/bi/data-catalog', icon: Database },
      { label: 'ETL Pipelines', href: '/bi/etl', icon: GitBranch },
    ],
  },
  {
    title: 'Collaboration',
    items: [
      { label: 'Team Chat', href: '/collab/chat', icon: MessagesSquare },
      { label: 'Workspaces', href: '/collab/workspaces', icon: FolderKanban },
      { label: 'Meetings', href: '/collab/meetings', icon: Video },
      { label: 'Knowledge Base', href: '/collab/knowledge', icon: BookOpen },
      { label: 'Announcements', href: '/collab/announcements', icon: Megaphone },
      { label: 'Directory', href: '/collab/directory', icon: Contact },
      { label: 'Activity', href: '/collab/activity', icon: Activity },
      { label: 'Whiteboard', href: '/collab/whiteboard', icon: PenTool },
    ],
  },
  {
    title: 'Marketplace',
    items: [
      { label: 'App Store', href: '/marketplace', icon: Store },
      { label: 'AI Agents', href: '/marketplace/agents', icon: Bot },
      { label: 'Theme Store', href: '/marketplace/themes', icon: Palette },
      { label: 'Templates', href: '/marketplace/templates', icon: FileText },
      { label: 'Developer Portal', href: '/developers', icon: Code },
    ],
  },
  {
    title: 'System',
    items: [
      { label: 'Audit Log', href: '/audit-log', icon: Shield },
      { label: 'Settings', href: '/settings', icon: Settings },
    ],
  },
  {
    title: 'Platform',
    items: [
      { label: 'Super Admin', href: '/super-admin', icon: Building2, badge: 'Admin' },
      { label: 'Tenants', href: '/super-admin/tenants', icon: Users },
      { label: 'Subscriptions', href: '/super-admin/subscriptions', icon: CreditCard },
      { label: 'Franchises', href: '/super-admin/franchises', icon: Globe },
      { label: 'API Platform', href: '/super-admin/api-platform', icon: Key },
      { label: 'Usage', href: '/super-admin/usage', icon: TrendingUp },
      { label: 'Domains', href: '/super-admin/domains', icon: Server },
    ],
  },
];
